In [19]:
import numpy as np
import pandas as pd

In [13]:
X = [[1000,2],[1400,3],[1500,3]]
y = [60,70,100]

In [21]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [22]:
model.predict([[2000,4]])

array([140.])

In [23]:
data = pd.read_csv("C:/Users/NICE/Desktop/Python_files/hp_data.csv")

In [24]:
data.head()

Unnamed: 0     price       place                 built  sqft    sale  \
0        1341   6300000  BTM Layout  Super built-up  Area  1450  Resale   
1        2126  11500000   Yelahanka  Super built-up  Area  2190  Resale   
2         816   3800000  Whitefield  Super built-up  Area  1019  Resale   
3        2708  10500000  Ambalipura  Super built-up  Area  1857  Resale   
4        1041  11500000   Yelahanka  Super built-up  Area  2190  Resale   

   yearsOld  floor  totalFloor  bhk  
0         5      1           4    1  
1         5      3           5    3  
2         1      2           5    2  
3        15      4           5    4  
4         5      3           5    3

In [25]:
data.shape

(3500, 10)

In [29]:
X = data.loc[:,['sqft','yearsOld','floor','totalFloor','bhk']]
y = data.price

In [30]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [31]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [33]:
model.predict([[4000,2,1,5,2]])

array([30315732.97843913])

In [62]:
from sklearn.model_selection import train_test_split
X_test, X_train, y_test, y_train  = train_test_split(X,y, test_size = 0.3, random_state = 10)
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [63]:
y_predict = model.predict(X_test)

In [64]:
from sklearn.metrics import r2_score
r2_score(y_test,y_predict)

0.8358984031630992

In [65]:
y_test.head(10)

3399    11500000
945      6300000
881     11500000
675     11500000
2127     6300000
1432     4800000
1143     4900000
1628     6300000
2486     4900000
2229     4900000
Name: price, dtype: int64

In [66]:
y_predict[5:10]

array([6397617.80328081, 1492443.51641889, 7810020.95130876,
       1492443.51641889, 1492443.51641889])